name: Publish
on: [push, workflow_run]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:15-jdk
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew build javadocJar publish --stacktrace
        env:
          MAVEN_PUBLISH_TOKEN: ${{ secrets.MAVEN_PUBLISH_TOKEN }}
